/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modul6Lanjutan;

import Modul6.Kuis2;

/**
 *
 * @author Nisrina Izdihar
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan1
     */
    public Frame1() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Kelas = new javax.swing.JLabel();
        Jurusan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Absen = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        Combo = new javax.swing.JComboBox<>();
        rdbRPL = new javax.swing.JRadioButton();
        rdbTKJ = new javax.swing.JRadioButton();
        Submit = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIODATA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(93, 18, 250, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NAMA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 70, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ABSEN");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 110, 60, 30);

        Kelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Kelas.setText("KELAS");
        jPanel1.add(Kelas);
        Kelas.setBounds(40, 150, 60, 30);

        Jurusan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jurusan.setText("JURUSAN");
        jPanel1.add(Jurusan);
        Jurusan.setBounds(40, 180, 90, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ALAMAT");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 220, 80, 40);
        jPanel1.add(Nama);
        Nama.setBounds(140, 70, 210, 30);
        jPanel1.add(Absen);
        Absen.setBounds(140, 110, 210, 30);
        jPanel1.add(Alamat);
        Alamat.setBounds(140, 220, 200, 30);

        Combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X RPL 1", "X RPL 2", "X RPL 3", "X RPL 4", "X RPL 5", "X RPL 6", "X RPL 7", "X TKJ 1", "X TKJ 2", "X TKJ 3", "X TKJ 4", "X TKJ 5", "X TKJ 6" }));
        jPanel1.add(Combo);
        Combo.setBounds(140, 150, 100, 30);

        buttonGroup1.add(rdbRPL);
        rdbRPL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbRPL.setText("RPL");
        jPanel1.add(rdbRPL);
        rdbRPL.setBounds(140, 183, 70, 30);

        buttonGroup1.add(rdbTKJ);
        rdbTKJ.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbTKJ.setText("TKJ");
        jPanel1.add(rdbTKJ);
        rdbTKJ.setBounds(260, 183, 70, 30);

        Submit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit);
        Submit.setBounds(70, 280, 110, 40);

        Exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Exit.setText("EXIT");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit);
        Exit.setBounds(200, 280, 110, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 380);

        setBounds(0, 0, 416, 415);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        String nm, abs, jur, alamat;
        String kelas = Combo.getSelectedItem().toString();
        nm = Nama.getText();
        abs = Absen.getText();
        alamat = Alamat.getText();
        
        //jurusan
        if(rdbRPL.isSelected()){
            jur = "RPL";
            if(Combo.getSelectedItem()=="X RPL 1"){
            }
            if(Combo.getSelectedItem()=="X RPL 2"){
            }
            if(Combo.getSelectedItem()=="X RPL 3"){
            }
            if(Combo.getSelectedItem()=="X RPL 4"){
            }
            if(Combo.getSelectedItem()=="X RPL 5"){
            }
            if(Combo.getSelectedItem()=="X RPL 6"){
            }
            if(Combo.getSelectedItem()=="X RPL 7"){
            }
        }else if(rdbTKJ.isSelected()){
            jur = "TKJ";
            if(Combo.getSelectedItem()=="X TKJ 1"){
            }
            if(Combo.getSelectedItem()=="X TKJ 2"){
            }
            if(Combo.getSelectedItem()=="X TKJ 3"){
            }
            if(Combo.getSelectedItem()=="X TKJ 4"){
            }
            if(Combo.getSelectedItem()=="X TKJ 5"){
            }
            if(Combo.getSelectedItem()=="X TKJ 6"){
        }
        }else {jur = "";}
        
         new Frame2(nm, abs, jur, alamat,kelas).setVisible(true);
    }//GEN-LAST:event_SubmitActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JTextField Alamat;
    private javax.swing.JComboBox<String> Combo;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Jurusan;
    private javax.swing.JLabel Kelas;
    private javax.swing.JTextField Nama;
    private javax.swing.JButton Submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdbRPL;
    private javax.swing.JRadioButton rdbTKJ;
    // End of variables declaration//GEN-END:variables
}
