/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modul6Lanjutan;

import javax.swing.JOptionPane;

/**
 *
 * @author Nisrina Izdihar
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SisiKubus = new javax.swing.JTextField();
        BtnVol = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Volume = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Jarijari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Hitung = new javax.swing.JButton();
        Panjang = new javax.swing.JTextField();
        Lebar = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROGRAM PENCARI VOLUME BANGUN RUANG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 20, 420, 50);

        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Masukkan Panjang Sisi");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(24, 23, 190, 30);
        jPanel1.add(SisiKubus);
        SisiKubus.setBounds(20, 60, 140, 30);

        BtnVol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnVol.setText("Volume");
        BtnVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVol);
        BtnVol.setBounds(30, 120, 120, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(170, 50, 40, 40);

        jTabbedPane1.addTab("KUBUS", jPanel1);

        jPanel4.setLayout(null);

        Volume.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Volume.setText("Volume");
        Volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeActionPerformed(evt);
            }
        });
        jPanel4.add(Volume);
        Volume.setBounds(20, 110, 120, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Masukkan Panjang Jari-jari");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 30, 240, 30);
        jPanel4.add(Jarijari);
        Jarijari.setBounds(20, 60, 210, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("cm");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(240, 50, 50, 40);

        jTabbedPane1.addTab("BOLA", jPanel4);

        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Masukkan Panjang :");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 11, 170, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Masukkan Lebar :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 50, 160, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Masukkan Tinggi :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 100, 150, 30);

        Hitung.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel3.add(Hitung);
        Hitung.setBounds(130, 170, 120, 40);
        jPanel3.add(Panjang);
        Panjang.setBounds(180, 20, 130, 30);
        jPanel3.add(Lebar);
        Lebar.setBounds(180, 60, 130, 30);
        jPanel3.add(Tinggi);
        Tinggi.setBounds(180, 100, 130, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("cm");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(320, 20, 50, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("cm");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(320, 60, 40, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("cm");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(320, 100, 60, 30);

        jTabbedPane1.addTab("BALOK", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 70, 430, 270);

        setSize(new java.awt.Dimension(444, 374));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        int p, l, t;
        p = Integer.parseInt(Panjang.getText());
        l = Integer.parseInt(Lebar.getText());
        t = Integer.parseInt(Tinggi.getText());
        int hasil = p * l * t;
        
        try{
            JOptionPane.showMessageDialog(null, "Volume Balok Adalah : " + hasil, "luas", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error : " + e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_HitungActionPerformed

    private void BtnVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolActionPerformed
        // TODO add your handling code here:
        int s;
        s = Integer.parseInt(SisiKubus.getText());
        int hasil = s * s * s;
        
        try{
            JOptionPane.showMessageDialog(null, "Luas permukaan kubus Adalah : " + hasil, "luas", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : " + e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnVolActionPerformed

    private void VolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeActionPerformed
        // TODO add your handling code here:
        float r;
        r = Integer.parseInt(Jarijari.getText());
        float hasil = (float) (4/3 * 3.14 * r * r * r);
        
        try{
            JOptionPane.showMessageDialog(null, "Luas permukaan bola Adalah : " + hasil, "luas", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : " + e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VolumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVol;
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField Jarijari;
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField SisiKubus;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton Volume;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
